# Generated by Django 4.1.1 on 2022-09-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_email_alter_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Proyecto',
        ),
    ]
