# Generated by Django 4.1.1 on 2022-10-01 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0003_rename_project_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_registrado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
