# Generated by Django 4.1.1 on 2022-10-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_usuario_registrado_alter_proyecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_registrado',
            name='moneda',
            field=models.CharField(choices=[('1', 'COP'), ('2', 'USD'), ('3', 'RUP')], default='1', max_length=20),
        ),
    ]
