# Generated by Django 4.1.1 on 2022-10-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0005_usuario_registrado_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregar_moneda',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dinero', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario_registrado',
            name='moneda',
            field=models.CharField(max_length=200),
        ),
    ]
