# Generated by Django 4.1.1 on 2022-10-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_agregar_moneda_alter_usuario_registrado_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar_moneda',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.usuario_registrado'),
        ),
    ]
