# Generated by Django 4.1.1 on 2022-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_agregar_moneda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar_moneda',
            name='dinero',
            field=models.FloatField(max_length=200),
        ),
    ]
