# Generated by Django 4.1.1 on 2022-10-01 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_agregar_moneda_dinero'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar_moneda',
            name='fecha_carga',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
