# Generated by Django 4.1.1 on 2022-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_agregar_moneda_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar_moneda',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
